import { AddressData } from "../work-address-edit/address-data";

export interface BasicData{
    First_Name__c: string, 
    Last_Name__c :string,
    Custom_Barcode__c:string,
    Email__c:string,
    DOB__c:string,
    Gender__c:string,
    Age__c:string,
    Home_Phone__c:string,
    Work_Phone__c:string,
    Mobile__c:string,
    TKT_Job_Title__c:string,
    TKT_Company__c:string,
    Prefix__c:string,
    Suffix__c:string,
    verify_Email__c:string,
    DBA__c:string,
    Company_Logo__c:string,
    User_Pic__c:string,
    FaceBookId__c:string,
    LinkedInId__c:string,
    TwitterId__c:string,
    Instagram__c:string,
    Video__c:string,
    Home_Address__r:AddressData,
    Work_Address__r:AddressData,
    Billing_Address__r:AddressData,
  }